version: 0.0
os: linux
files:
  - source: master.d/
    destination: /etc/salt/master.d/
  - source: minion.d
    destination: /etc/salt/minion.d/
  - source: pillars/
    destination: /etc/salt/pillars/
  - source: states/
    destination: /etc/salt/states/
hooks:
  ApplicationStart:
    - location: deploy_hooks/start_service.sh
      runas: root
  ApplicationStop:
    - location: deploy_hooks/stop_service.sh
      runas: root
  ValidateService:
    - location: deploy_hooks/verify_service.sh
      runas: root